language: node_js
node_js:
- "0.12"
cache:
    directories:
    - node_modules
sudo: false
addons:
    postgresql: "9.4"
    apt:
        packages:
        - libcairo2-dev
        - libjpeg8-dev
        - libpango1.0-dev
        - libgif-dev
        - build-essential
        - g++
before_script: psql -c 'create database continua11y_test;' -U postgres
script: npm test
after_script: ./test/continua11y.sh
notifications:
    email: false
env:
    global:
    - RUN_SCRIPT="FRESHDB=TRUE forever start --spinSleepTime 5000 --minUptime 5000 app.js"
    - KILL_SCRIPT="forever stop app.js"
    - USE_SITEMAP=false
    - PORT=3000
    - CONTINUA11Y="continua11y.herokuapp.com"